---

- name: Try to install bpytop from apt (if available)
  ansible.builtin.apt:
    name: bpytop
    state: present
    update_cache: no
  register: bpytop_apt_install
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Verify bpytop is installed (binary found)
  ansible.builtin.command: "which bpytop"
  register: bpytop_path
  changed_when: false
  failed_when: bpytop_path.rc != 0

- name: Print bpytop version (for debug)
  ansible.builtin.command: bpytop --version
  register: bpytop_ver
  changed_when: false

- name: Show bpytop install info
  ansible.builtin.debug:
    msg:
      - "bpytop binary: {{ bpytop_path.stdout }}"
      - "bpytop version: {{ bpytop_ver.stdout }}"