# --- Debian/Ubuntu only ---
- name: Update apt cache if older than 1 hour
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure prerequisites for Docker repo
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_os_family == "Debian"

- name: Download Docker GPG key (ASCII)
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"
  when: ansible_os_family == "Debian"

- name: Convert GPG key to keyring (.gpg)
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc"
    creates: "/etc/apt/keyrings/docker.gpg"
  when: ansible_os_family == "Debian"

- name: Ensure keyring perms are world-readable
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: "0644"
  when: ansible_os_family == "Debian"

# Raspberry Pi note: map Ansible arch to Docker's apt arch names
- name: Map architecture for Docker repo
  ansible.builtin.set_fact:
    docker_apt_arch: >-
      {{ 'arm64' if ansible_architecture in ['aarch64','arm64'] else
         'armhf' if ansible_architecture in ['armv7l','armhf'] else
         'amd64' if ansible_architecture in ['x86_64','amd64'] else
         ansible_architecture }}
  when: ansible_os_family == "Debian"

- name: Add Docker apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
    content: |
      deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  when: ansible_os_family == "Debian"

- name: Install Docker engine, CLI, containerd, buildx and compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
